# Generated by Django 3.2.9 on 2022-05-06 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_wishlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='products',
            name='slug',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='products',
            name='small_description',
            field=models.TextField(),
        ),
    ]
